name: Syntax Error Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run command
        run: |
          echo "This will fail"
          python -c "print('missing quote)