name: Timeout Error
on: [push]
jobs:
  long-running:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3
      - name: Long running process
        run: |
          echo "Starting long process..."
          sleep 120
          echo "This won't be reached"